# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ctis-bangkok',
                'doc_host': 'https://calremmel.github.io',
                'git_url': 'https://github.com/calremmel/ctis-bangkok',
                'lib_path': 'ctis_bangkok'},
  'syms': {'ctis_bangkok.core': {'ctis_bangkok.core.foo': ('core.html#foo', 'ctis_bangkok/core.py')}}}